.TH "lightdm-webkit2-greeter" "1" "2016.01.10"
.nh
.ad l
.SH "NAME"
lightdm-webkit2-greeter
.SH "SYNOPSIS"
.PP
LightDM greeter that uses webkit2 for theming via HTML/JavaScript\&.
.PP
.SH "DESCRIPTION"
.PP
lightdm-webkit2-greeter is a LightDM greeter that uses webkit2 for theming\&.  Themes can be written
using a combination of HTML and Javascript\&.
.PP
.SH "THEME JAVASCRIPT API"
Please note that all properties and functions which are marked as "deprecated" are
only available for backwards compatibility and will be removed in a future version of
lightdm-webkit2-greeter\&.  Theme authors should not use any deprecated properties or
functions in new works and should update any existing works which make use of
deprecated properties and/or functions to ensure continued proper functionality\&.
.PP
The following functions \fBmust\fR be provided by the greeter theme and callable on the global "window" object\&.
.PP
\fBshow_prompt(text, type)\fR
.RS 4
This will be called when LightDM needs to prompt the user for some reason, such
as asking for a password\&.  The "text" parameter will be the text of the
prompt, and the "type" parameter will either be "text" for a visible prompt, or
"password" for a prompt that the input should be hidden\&.
.RE
.PP
\fBshow_message(text, type)\fR
.RS 4
This will be called when LightDM needs to display some info for the user\&.
The "text" parameter will be the text of the
message, and the "type" parameter will either be "info" for an information
message, or "error" for an error message that LightDM has encountered\&.
.RE
.PP
\fBauthentication_complete()\fR
.RS 4
This function is called by LightDM when authentication has completed\&.
.RE
.PP
\fBautologin_timer_expired()\fR
.RS 4
This function is called by LightDM when an autologin user's login timer has
expired\&.  The greeter should reset the authentication process\&.
.RE
.PP
The following functions are available for the greeter to call to execute
actions within LightDM\&.
.PP
\fBlightdm\&.authenticate(username)\fR
.RS 4
Specifies the username of the user we'd like to start authenticating as\&.  Note that
if you call lightdm.authenticate with no argument, LightDM (via PAM) will issue
a show_prompt() call to ask for the username\&. The older function
lightdm\&.start_authentication() has been deprecated\&.
.RE
.PP
\fBlightdm\&.authenticate_as_guest()\fR
.RS 4
Authenticates as the guest user\&.
.RE
.PP
\fBlightdm\&.cancel_authentication()\fR
.RS 4
Cancels the authentication of any user currently in the process of
authenticating\&.
.RE
.PP
\fBlightdm\&.cancel_autologin()\fR
.RS 4
Cancels the authentication of the autologin user\&.  The older function
lightdm\&.cancel_timed_login() has been deprecated.
.RE
.PP
\fBlightdm\&.get_hint(hint_name)\fR
.RS 4
Returns the value of a named hint provided by LightDM\&.
.RE
.PP
\fBlightdm\&.hibernate()\fR
.RS 4
Hibernates the system, if the greeter has the authority to do so\&.
.RE
.PP
\fBlightdm\&.start_session_sync(session)\fR
.RS 4
Once LightDM has successfully authenticated the user, start the user's session
by calling this function\&.  "session" is the authenticated user's session\&.
If no session is passed, start the authenticated user with the system default
session. The older function lightdm\&.login(user, session) has been
deprecated\&.
.RE
.PP
\fBlightdm\&.respond(text)\fR
.RS 4
When LightDM has prompted for input, provide the response to LightDM\&.
The deprecated function was "provide_secret"\&.  This is still available for
backwards compatibility, but authors of greeters should move to using
lightdm.respond()\&.
.RE
.PP
\fBlightdm\&.restart()\fR
.RS 4
Restarts the system, if the greeter has the authority to do so\&.
.RE
.PP
\fBlightdm\&.set_language(lang)\fR
.RS 4
Will set the language for the current LightDM session\&.
.RE
.PP
\fBlightdm\&.shutdown()\fR
.RS 4
Shuts down the system, if the greeter has the authority to do so\&.
.RE
.PP
Variables available within the greeter are:
.PP
\fBlightdm\&.authentication_user\fR
.RS 4
String\&. The username of the authentication user being authenticated or null if no
authentication is in progress\&.
.RE
.PP
\fBlightdm\&.autologin_guest\fR
.RS 4
Boolean\&. Indicates the guest user should be used for autologin\&.
.RE
.PP
\fBlightdm\&.autologin_timeout\fR
.RS 4
Number\&. The number of seconds to wait before automatically logging in\&. The
older variable lightdm\&.timed_user_delay has been deprecated\&.
.RE
.PP
\fBlightdm\&.autologin_user\fR
.RS 4
String\&. The name of the user account that should be logged into
automatically after timed login delay has passed\&. The older variable
lightdm\&.timed_login_user has been deprecated\&.
.RE
.PP
\fBlightdm\&.can_hibernate\fR
.RS 4
Boolean\&. Whether or not the system can be made to hibernate by the greeter\&.
.RE
.PP
\fBlightdm\&.can_restart\fR
.RS 4
Boolean\&. Whether or not the system can be restarted by the greeter\&.
.RE
.PP
\fBlightdm\&.can_shutdown\fR
.RS 4
Boolean\&. Whether or not the system can be shutdown by the greeter\&.
.RE
.PP
\fBlightdm\&.can_suspend\fR
.RS 4
Boolean\&. Whether or not the system can be suspended by the greeter\&.
.RE
.PP
\fBlightdm\&.default_session\fR
.RS 4
String\&. The name of the default session (as configured in lightdm.conf)\&.
.RE
.PP
\fBlightdm\&.has_guest_account\fR
.RS 4
Boolean\&. A guest account is available for login\&.
.RE
.PP
\fBlightdm\&.hide_users\fR
.RS 4
Boolean\&. The whole list of users should not be displayed\&.
.RE
.PP
\fBlightdm\&.hostname\fR
.RS 4
String\&. The hostname of the system\&.
.RE
.PP
\fBlightdm\&.is_authenticated\fR
.RS 4
Boolean\&. Indicates if the user has successfully authenticated\&.
.RE
.PP
\fBlightdm\&.in_authentication\fR
.RS 4
Boolean\&. Indicates if lightdm is currently in the authentication phase\&.
.RE
.PP
\fBlightdm\&.language\fR
.RS 4
String\&. The currently selected language\&. The older variable name
lightdm\&.default_language is deprecated\&.
.RE
.PP
\fBlightdm\&.layout\fR
.RS 4
String\&. The name of the currently active keyboard layout\&. To change the
layout, assign a valid layout name to this variable\&. The older variable name
lightdm\&.default_layout is deprecated\&.
.RE
.PP
\fBlightdm\&.layouts\fR
.RS 4
Array\&. The keyboard layouts that are available on the system\&. Returns an Array
of LightDMLayout objects\&.
.RE
.PP
\fBlightdm\&.num_users\fR
.RS 4
Number\&. The number of users able to log in\&.
.RE
.PP
\fBlightdm\&.select_guest\fR
.RS 4
Boolean\&. The guest user should be selected by default for login\&.
.RE
.PP
\fBlightdm\&.select_user\fR
.RS 4
String\&. The username that should be selected by default for login\&.
.RE
.PP
\fBlightdm\&.sessions\fR
.RS 4
Array\&. The sessions that are available on the system\&. Returns an Array of
LightDMSession objects\&.
.RE
.PP
\fBlightdm\&.users\fR
.RS 4
Array\&. The users that are able to log in\&. Returns an Array of LightDMUser
objects\&.
.RE
.PP
The following calls can be made to read configuration keys out of the
lightdm-webkit2-greeter configuration file\&.
.PP
config\&.get_str(section, key)\fR
.RS 4
Returns the string value associated with key under the "section" in the configuration file\&.
.RE
.PP
config\&.get_num(section, key)\fR
.RS 4
Returns the numeric value associated with key under the "section" in the configuration file\&.
.RE
.PP
config\&.get_bool(section, key)\fR
.RS 4
Returns the boolean value associated with key under the "section" in the configuration file\&.
.RE
.PP
The greeterutil object has some utility functions associated with it which
are intended to make a theme author's work easier\&.
.PP
greeterutil\&.dirlist(path)\fR
.RS 4
Returns an array of strings of filenames present at "path", or Null if the
path does not exist\&.
.RE
.PP
greeterutil\&.txt2html(txt)\fR
.RS 4
Returns a simple HTML conversion of the passed text\&.  Newlines are replaced
with <br>, and the characters \&&, <, >, and " are replaced with their HTML
equivalents\&.
.RE
.PP
Please see the LightDM API documentation for the complete list of calls
available\&.  The lightdm-webkit2-greeter implements all of the LightDM API\&.
.PP
.SH "CONFIGURATION"
.PP
\fB/etc/lightdm/lightdm-webkit2-greeter\&.conf\fR
.RS 4
Keyfile that contains one key: webkit-theme\&.  This should point to which
theme the greeter should use\&.
.RE
.SH "FILES"
.PP
\fB/usr/share/lightdm-webkit/themes\fR
.RS 4
Directory where themes should be stored\&.
.RE
.SH "EXAMPLES"
.PP
Please see the "antergos" and "simple" themes that are shipped with lightdm-webkit2-greeter\&.
.SH "SEE ALSO"
.PP
http://people\&.ubuntu\&.com/~robert-ancell/lightdm/reference/core\&.html
.SH "AUTHOR"
.PP
The legacy lightdm-webkit-greeter was written by Robert Ancell <robert\&.ancell\&@canonical\&.com\&>\&.
It was ported to webkit2 by the Antergos Developers <dev@antergos\&.com>\&. Also includes code improvements
contributed by Scott Balneaves <sbalneav@ltsp\&.org>\&.
